#!/bin/sh

echo 'Checking for project linting, formatting, typescript, and build issues 🏗️👷'

pnpm run check:lint ||
(
    echo 'Linting issues found ❌' Please run `npm run lint` to fix this automatically.
    false;
)

pnpm run check:format ||
(
    echo 'Formatting issues found ❌ Please run `npm run format` to fix this automatically.';
    false;
)

pnpm run check:types ||
(
    echo 'TypeScript issues found ❌'
    false;
)

pnpm run build ||
(
    echo 'Build issues found ❌'
    false;
)

echo 'No issues found ✅'
