name: Run Code Quality Checks and Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Run lint check
        run: pnpm run check:lint

  prettier-check:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack (pnpm)
        run: corepack enable       

      - name: Install dependencies
        run: pnpm install

      - name: Run prettier check
        run: pnpm run check:format

  typescript-check:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript check
        run: pnpm run check:types

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Run build check
        run: pnpm run build
